import Head from 'next/head'
import React from 'react'
import Header from '../components/Header'

const cart = () => {
  return (
    <>
    <Head>
      <title>E-Commerce</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header></Header>

    <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
      
    </main>
  </>
  )
}

export default cart