import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  //const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const product = trpc.product.getAll.useQuery().data;

  console.log(product);

  return (
    <>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        
      </main>
    </>
  );
};

export default Home;

type CardProps = {
  name: string;
  slug: string;
  description: string;
  inventary: number;
  price: number;
};

const Card: React.FC<CardProps> = ({
  name,
  slug,
  description,
  inventary,
  price,
}) => {
  return (
    <section className="flex flex-col justify-center rounded border-2 border-gray-500 p-6 shadow-xl duration-500 motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{slug}</p>
      <p className="text-sm text-gray-600">{price}</p>
      <Link
        className="m-auto mt-3 w-fit text-sm text-violet-500 underline decoration-dotted underline-offset-2"
        href={description}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </Link>
    </section>
  );
};
